/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.FindIterable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import org.bson.Document;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harsh
 */
public class adder extends javax.swing.JFrame {

    /**
     * Creates new form adder
     */
    public adder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BOARDING STATION : ");

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel3.setBackground(new java.awt.Color(255, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("FIND MY TRAIN");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("DESTINATION STATION: ");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 144, Short.MAX_VALUE)))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 28, 400, 280));

        jLabel4.setBackground(new java.awt.Color(102, 0, 102));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uri = "mongodb+srv://harshasri1511:Harshasrigee@harsha.6gp0f.mongodb.net/?retryWrites=true&w=majority&appName=Harsha";

        try (MongoClient mongoClient = MongoClients.create(uri)) {
            // Step 2: Select the database and collection
            MongoDatabase database = mongoClient.getDatabase("train");
            MongoCollection<Document> collection = database.getCollection("details");

            // Step 3: Query MongoDB collection to fetch all documents (no filters)
            FindIterable<Document> results = collection.find(); // This will fetch all the train records

            // Step 4: Create the container for all train results
            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS)); // Stack elements vertically

            // Step 5: Iterate over each document and prepare UI components
            for (Document doc : results) {
                // Create a panel for each train item
                JPanel trainPanel = new JPanel();
                trainPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));  // Left-aligned with small gap
                trainPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1)); // Border for each train item
                trainPanel.setPreferredSize(new Dimension(500, 70)); // Set preferred size to make it clickable
                trainPanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  // Change cursor to hand to indicate clickability

                // Left part (Train Number + Boarding Time)
                JPanel leftPanel = new JPanel();
                leftPanel.setLayout(new BoxLayout(leftPanel, BoxLayout.Y_AXIS)); // Stack vertically
                JLabel trainNoLabel = new JLabel("Train No: " + doc.getString("train-no"));
                JLabel boardingTimeLabel = new JLabel("Boarding Time: " + doc.getString("btime"));
                trainNoLabel.setFont(new Font("Arial", Font.PLAIN, 12));
                boardingTimeLabel.setFont(new Font("Arial", Font.PLAIN, 12));
                leftPanel.add(trainNoLabel);
                leftPanel.add(boardingTimeLabel);

                // Right part (Train Name + Destination Time)
                JPanel rightPanel = new JPanel();
                rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.Y_AXIS)); // Stack vertically
                JLabel trainNameLabel = new JLabel("Train Name: " + doc.getString("train-name"));
                JLabel destinationTimeLabel = new JLabel("Destination Time: " + doc.getString("dtime"));
                trainNameLabel.setFont(new Font("Arial", Font.PLAIN, 12));
                destinationTimeLabel.setFont(new Font("Arial", Font.PLAIN, 12));
                rightPanel.add(trainNameLabel);
                rightPanel.add(destinationTimeLabel);

                // Add both left and right panels to the main train panel
                trainPanel.add(leftPanel);
                trainPanel.add(rightPanel);

                // Add MouseListener to the train panel to make it clickable
                trainPanel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        // When a train panel is clicked, open a new frame with the train details
                        showdetails.openTrainDetailsPage(doc);  // Open the train details in a new frame
                    }
                });

                // Add the train panel to the main panel (scrollable container)
                mainPanel.add(trainPanel);
            }

            // Step 6: Create and display the JScrollPane with the main panel (scrollable)
            JScrollPane scrollPane = new JScrollPane(mainPanel);
            scrollPane.setPreferredSize(new Dimension(600, 400));  // Set the scrollable pane's preferred size
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);  // Always show the vertical scrollbar

            // Step 7: Create JFrame for display
            JFrame frame = new JFrame("Train Search Results");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLayout(new BorderLayout());

            // Step 8: Create header for the window
            JLabel header = new JLabel("All Train Details", JLabel.CENTER);
            header.setFont(new Font("Arial", Font.BOLD, 20));
            header.setBackground(new Color(70, 130, 180));  // Header color
            header.setForeground(Color.WHITE);
            header.setOpaque(true);
            header.setPreferredSize(new Dimension(600, 40));  // Header height

            // Step 9: Create the Back button
            JButton backButton = new JButton("Back");
            backButton.setBackground(new Color(70, 130, 180));
            backButton.setForeground(Color.WHITE);
            backButton.setFont(new Font("Arial", Font.PLAIN, 14));
            backButton.addActionListener(e -> {
                frame.dispose();  // Close the current frame
            });

            // Add components to frame
            frame.add(header, BorderLayout.NORTH);  // Add header at the top
            frame.add(scrollPane, BorderLayout.CENTER);  // Add scrollable list to the center
            frame.add(backButton, BorderLayout.SOUTH);  // Add back button at the bottom

            // Show the frame
            frame.pack();
            frame.setLocationRelativeTo(null);  // Center the frame
            frame.setVisible(true);

            System.out.println("All train records fetched successfully");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
